/*****************************************************************************
* Model: icbm.qm
* File:  ./icbm.h
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/*${.::icbm.h} .............................................................*/
/* Allegro A4960 BLDC test fixture main header */
#ifndef bldc_meter_h
#define bldc_meter_h

/* from MC controller RPM = (FG*720)/P*S */


#define REV "0"

enum BldcMeterSignals {                       /* signals used in the meter */

    TIME_TICK_SIG = Q_USER_SIG,
    WCOL_SIG,    //SPI write collision
    BLINK_SIG,
    ALARM_SIG,
    RUN_SIG,
    /**/
    TACHO_SIG,
    TACHO_TIMEOUT_SIG,
    RPM_SIG,
    FF_SIG,
    KBD_KEY_SIG,
    RBUT_PRESS_SIG,
    RBUT_RELEASE_SIG,
    BBUT_PRESS_SIG,
    BBUT_RELEASE_SIG
};
/* Access to A4960 fields */

/* active objects ..........................................................*/
extern struct Console  AO_Console;

/*${AOs::Console_ctor} .....................................................*/
void Console_ctor(void);


#endif                                                      /* bldc_meter_h */
